package com.lifeistech.android.schoolseventeen.junjun.spicekigen;
import io.realm.RealmObject;
import io.realm.annotations.Ignore;

/**
 * Created by junekelectric on 2017/09/09.
 */

public class Food extends RealmObject {
    public String mcontent;

    @Ignore
    public String mtitle;
    public String mdate;

    // Standard getters & setters generated by your IDE…
    public String getMtitle() { return mtitle; }
    public void   setMtitle(String mtitle) { this.mtitle = mtitle; }
    public String getMdate() { return mdate; }
    public void   setMdate(String mdate) { this.mdate = mdate; }
    public String getMcontent() { return mcontent; }
    public void   setMcontent(String mcontent) { this.mtitle = mcontent; }
}

